#ENTRYPOINT used to provide the command executed by the container when it is started.
FROM almalinux:9
#CMD ["ping","google.com"]
#ENTRYPOINT ["ping","google.com"]
CMD [ "google.com" ]
ENTRYPOINT [ "ping" ]