#Label adds the metadata to the image, used for filteration
# alamalinux is exactly same as Redhat image, but completely free
FROM alamalinux:9
LABEL COURSE="Docker" \
      TRAINER="ShivaKumar" \
      DURATION="10HRS"
