#Label adds the metadata to the image, used for filteration
# almalinux is exactly same as Redhat image, but completely free
FROM almalinux:9
LABEL COURSE="Docker" \
      TRAINER="Sivakumar" \
      DURATION="10HRS" \
      AUTHOR="joindevops"
