# Used to copy the files from local to image, but it has 2 extra capabilities
#1. It can fetch the content directly from internet
#2. It can untar the content directly in the image
FROM almalinux:9
ADD https://github.com/ganil-kumar/roboshop-documentation /tmp
